name: project_listapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  supabase_flutter: ^1.10.25
  flutter_secure_storage: ^9.0.0
  badges: ^3.1.2
  flutter_svg: ^2.0.9
  qr_code_scanner: ^1.0.1
  table_calendar: ^3.0.9
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  

flutter:
  uses-material-design: true
assets:
  - assets/icons/